import {
  Calendar,
  Users,
  TrendingUp,
  Package,
  MessageCircle,
  Gift,
  Building2,
  BarChart3,
  Clock,
  Shield,
  Zap,
  Smartphone,
} from "lucide-react";
import { assets } from "../../assets/assets";

export const mainFeatures = [
  {
    icon: Calendar,
    title: "Smart Appointment System",
    description:
      "Never lose another booking with our intelligent scheduling system",
    features: [
      "Real-time calendar with conflict detection",
      "Walk-in management with queue system",
      "Automatic SMS and WhatsApp reminders",
      "Online booking widget for your website",
      "Staff availability management",
      "Recurring appointment setup",
    ],
    benefit: "35% fewer no-shows",
    color: "white",
    logo: assets.appointment,
  },
  {
    icon: Users,
    title: "Staff Performance Tracking",
    description: "Know exactly who's making you money with detailed analytics",
    features: [
      "Individual staff performance metrics",
      "Automatic commission calculations",
      "Working hours and leave management",
      "Service-wise revenue tracking",
      "Customer feedback per staff member",
      "Incentive and bonus management",
    ],
    benefit: "20% increase in staff productivity",
    color: "white",
    logo: assets.performance,
  },
  {
    icon: TrendingUp,
    title: "Revenue-Boosting Billing",
    description:
      "Professional invoicing that increases your average ticket size",
    features: [
      "GST-compliant invoice generation",
      "Multiple payment methods support",
      "Package deals and combo offers",
      "Upselling recommendations",
      "Split payment options",
      "Automatic tax calculations",
    ],
    benefit: "25% higher average ticket size",
    color: "white",
    logo: assets.revenue,
  },
  {
    icon: Package,
    title: "Smart Inventory Management",
    description: "Never run out of products or overspend on inventory",
    features: [
      "Real-time stock level monitoring",
      "Automatic reorder alerts",
      "Product usage tracking per service",
      "Supplier management system",
      "Cost analysis and profit margins",
      "Barcode scanning support",
    ],
    benefit: "30% reduction in inventory costs",
    color: "white",
    logo: assets.revenue,
  },
  {
    icon: MessageCircle,
    title: "Customer Retention Automation",
    description: "Bring customers back automatically with smart campaigns",
    features: [
      "Automated WhatsApp follow-ups",
      "Birthday and anniversary campaigns",
      "Service reminder notifications",
      "Feedback collection system",
      "Win-back campaigns for lost customers",
      "Personalized offers based on history",
    ],
    benefit: "40% increase in repeat customers",
    color: "white",
    logo: assets.customer,
  },
  {
    icon: Gift,
    title: "Loyalty & Membership System",
    description: "Turn one-time visitors into lifetime customers",
    features: [
      "Points-based loyalty program",
      "Prepaid package management",
      "Referral reward system",
      "VIP customer tiers",
      "Cashback and discount campaigns",
      "Membership card generation",
    ],
    benefit: "50% increase in customer lifetime value",
    color: "white",
    logo: assets.membership,
  },
  {
    icon: Building2,
    title: "Multi-Location Management",
    description: "Manage unlimited salons from one powerful dashboard",
    features: [
      "Centralized dashboard for all locations",
      "Location-specific reports and analytics",
      "Staff transfer between branches",
      "Inventory sharing across locations",
      "Franchise performance comparison",
      "Role-based access control",
    ],
    benefit: "15+ hours saved weekly for franchise owners",
    color: "white",
    logo: assets.membership,
  },
  {
    icon: BarChart3,
    title: "Advanced Analytics & Reports",
    description: "Make data-driven decisions with comprehensive insights",
    features: [
      "Revenue and profit analysis",
      "Customer behavior insights",
      "Staff performance comparison",
      "Service popularity tracking",
      "Peak hours and seasonal trends",
      "Custom report generation",
    ],
    benefit: "Make decisions based on data, not guesswork",
    color: "white",
    logo: assets.analytic,
  },
];

export const additionalFeatures = [
  {
    icon: Clock,
    title: "Time Management",
    description: "Optimize your salon's time usage for maximum efficiency",
  },
  {
    icon: Shield,
    title: "Data Security",
    description: "Bank-level security to protect your customer data",
  },
  {
    icon: Zap,
    title: "Fast Performance",
    description: "Lightning-fast system that works even during peak hours",
  },
  {
    icon: Smartphone,
    title: "Mobile App",
    description: "Manage your salon on-the-go with our mobile application",
  },
];
